import requests
import json

# Test data with new drugs
test_cases = [
    # New drugs from SECTION 1: PAIN & FEVER
    {
        "name": "Dolo (Paracetamol) for Fever",
        "data": {
            "age": 35,
            "gender": "M",
            "ethnicity": "Asian",
            "condition": "fever",
            "drug": "dolo",
            "past_reaction": "no"
        }
    },
    {
        "name": "Crocin (Paracetamol) for Fever",
        "data": {
            "age": 45,
            "gender": "F",
            "ethnicity": "African",
            "condition": "fever",
            "drug": "crocin",
            "past_reaction": "no"
        }
    },
    {
        "name": "Ibuprofen for Pain",
        "data": {
            "age": 40,
            "gender": "M",
            "ethnicity": "Hispanic",
            "condition": "fever",
            "drug": "ibuprofen",
            "past_reaction": "no"
        }
    },
    
    # New drugs from SECTION 2: ANTIBIOTICS
    {
        "name": "Azithromycin (Azee) for Infection",
        "data": {
            "age": 30,
            "gender": "F",
            "ethnicity": "Asian",
            "condition": "infection",
            "drug": "azee",
            "past_reaction": "no"
        }
    },
    {
        "name": "Ciprofloxacin (Cipro) for Infection",
        "data": {
            "age": 55,
            "gender": "M",
            "ethnicity": "Caucasian",
            "condition": "infection",
            "drug": "cipro",
            "past_reaction": "no"
        }
    },
    
    # New drugs from SECTION 3: CARDIAC & DIGESTIVE
    {
        "name": "Pantoprazole (Pan) for Digestion",
        "data": {
            "age": 60,
            "gender": "M",
            "ethnicity": "Asian",
            "condition": "digestion",
            "drug": "pan",
            "past_reaction": "no"
        }
    },
    {
        "name": "Amlodipine (Norvasc) for Cardiac",
        "data": {
            "age": 65,
            "gender": "F",
            "ethnicity": "African",
            "condition": "cardiac",
            "drug": "norvasc",
            "past_reaction": "no"
        }
    },
    {
        "name": "Metformin for Diabetes",
        "data": {
            "age": 52,
            "gender": "M",
            "ethnicity": "Hispanic",
            "condition": "diabetes",
            "drug": "metformin",
            "past_reaction": "no"
        }
    },
    
    # Original drugs for comparison
    {
        "name": "Warfarin (Original) for Cardiac",
        "data": {
            "age": 70,
            "gender": "M",
            "ethnicity": "Caucasian",
            "condition": "cardiac",
            "drug": "warfarin",
            "past_reaction": "no"
        }
    },
]

print("🧪 Testing trained model with all drugs...")
print("=" * 80)

for i, test_case in enumerate(test_cases, 1):
    print(f"\n🔬 Test {i}: {test_case['name']}")
    print("-" * 80)
    
    try:
        response = requests.post(
            "http://127.0.0.1:8000/predict",
            json=test_case["data"],
            timeout=10
        )
        
        if response.status_code == 200:
            result = response.json()
            
            # Check if we got proper results
            if "error" not in result:
                print(f"✅ Success!")
                print(f"   Risk Level: {result.get('risk', 'N/A')}")
                print(f"   Confidence: {result.get('confidence', 0):.1%}")
                print(f"   Mapped Drug: {result.get('mapped_drug', 'N/A')}")
                
                # Check for AI explanation
                if result.get('reasons'):
                    print(f"   Reasons: {', '.join(result.get('reasons', []))}")
                else:
                    print(f"   ⚠️  No reasons provided")
                    
                if result.get('recommendation'):
                    print(f"   Recommendation: {result.get('recommendation', 'N/A')[:80]}...")
                else:
                    print(f"   ⚠️  No recommendation provided")
            else:
                print(f"❌ Error: {result.get('error', 'Unknown error')}")
        else:
            print(f"❌ HTTP Error: {response.status_code}")
            print(f"   Response: {response.text}")
    
    except requests.exceptions.ConnectionError:
        print(f"❌ Connection Error: Backend not responding at http://127.0.0.1:8000")
        break
    except Exception as e:
        print(f"❌ Error: {str(e)}")

print("\n" + "=" * 80)
print("✅ Testing complete!")
print("\nSummary:")
print("- All new drugs from 3 sections have been tested")
print("- Model should now provide non-zero confidence scores")
print("- AI explanations should be generated by Groq")
